# Generated by Django 5.2.6 on 2025-11-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='adventory',
            new_name='inventory',
        ),
    ]
